### ISSUE TITLE
Невозможно выплеснуть жидкости из инвентаря уборщика

### ISSUE THREAD

**Issue by kanoriano** [space-syndicate/space-station-14#1007]
### Описание

![image](https://user-images.githubusercontent.com/39070007/233235880-c2108f1c-904a-4bfd-a210-8eb59bb70d53.png)
![image](https://user-images.githubusercontent.com/39070007/233235987-af826bd7-db70-4bff-8c65-2d2494c38a5c.png)

Однако возможно выплеснуть взаимодействуя с предметами в руке
![image](https://user-images.githubusercontent.com/39070007/233236174-2d3cd796-dc0b-488f-b9bd-dca46e520764.png)

**Comment by lapatison** [comment]
Перетяни курсором ведро для швабры на дренаж на полу.

**Comment by lzk228** [comment]
может закрыть?
