### ISSUE TITLE
TG station спрайты для бригмедика

### ISSUE THREAD

**Issue by PuroSlavKing** [space-syndicate/space-station-14#1052]
### Описание

Убрать ТГшные спрайты. Уже даже спрайтеры с корвуха нарисовали вещи для бригмедика, а досихпор это полу-синдикатное гавно, или перерисуйте новые вещи бригмедика под стилистику ТГ (во делать вам нехуй, типо)

### Шаги воспроизведения

1. Посмотреть на ТГ униформу.
2. Блевануть.
3. Утилизировать ТГ форму.

### Скриншоты

![image](https://user-images.githubusercontent.com/103608145/236635737-fc482efc-b223-4ea5-a06c-8103f4fc9db9.png)

**Comment by lzk228** [comment]
wyci wysi susy

**Comment by PuroSlavKing** [comment]
> wyci wysi susy

ебейший вуси, целые текстуры поменять

**Comment by Morb0** [comment]
Who?
