### ISSUE TITLE
Не спавнятся карты

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1172]
### Описание

При старте раунда не спавнятся следующие карты:
- Bagel
- Box
- CorvaxBox
- Meta
- Fland
- CorvaxIshimura

Карты не спавнятся только на игровых серверах. На локальном сервере (дебаг и релиз сборка) всё работает отлично.

### Шаги воспроизведения

1. Проголосовать за багель
2. Дождатся начала раунда
3. Голосовать за рестарт раунда/ждать модерацию для перезапуска раунда
4. Голосвать не за багель

**Comment by NewNovus** [comment]
А можно хоть код ошибки, скриншот консоли, или что нибудь еще? 
Эфимерная проблемма получается, она (проблемма) есть, но доступа к ошибке нету. Ну просто если нет, нельзя, тогда вы между собой просто могли решить проблемму, не обязательно создавать ишью.

**Comment by lzk228** [comment]
В том то и дело, на игровых серверах в консоли клиента не отображается ошибка, а просто не загружается карта.
Как и говорил на локальном сервере ошибки нет, потому что карта загружается.

**Comment by NewNovus** [comment]
Понял, признал.

> в плане?
Между кодерами

**Comment by lzk228** [comment]
Ну, можно было пингагнуть Морти в разработке и сказать ему, но наверняка он уже знает. А так хоть глаза мозолить будет :trollface:

**Comment by VigersRay** [comment]
Понятно что в дебаге они будут загружаться. Ты на локалке пропиши -configuration=RELEASE (что является версией сборки для хостинга) и сразу в логах увидишь в чем проблема.
