### ISSUE TITLE
Не работает ТТС в лобби. 

### ISSUE THREAD

**Issue by LEVELcat** [space-syndicate/space-station-14#1442]
### Описание

В лобби, в разделе настроек персонажа не работает ТТС.
В самом раунде ТТС есть.

### Скриншоты

Видео с багом
https://github.com/space-syndicate/space-station-14/assets/68501903/28840f85-27c9-4d6d-bfbb-fc04c225253e

**Comment by lzk228** [comment]
проблема сборки?
это можно починить с помощью кодинга?
не думаю

**Comment by LEVELcat** [comment]
Странно что ТТС не работает только в лобби, а не в игре.
Не думаю, что проблема на стороне держателя ТТС.

**Comment by JerryImMouse** [comment]
ТТС работает, просто **ОЧЕНЬ** тихо, и с огромной задержкой.
Так что думаю проблема на стороне держателя ТТС

**Comment by Rxup** [comment]
смысл в том что клиент посылает `MsgRequestTTS` на сущность которая client side only и играет ее позицию на nullspace карты с помощью метода    
```
private void PlayEntity(AudioStream stream)
{
        if (!_entity.TryGetComponent<TransformComponent>(GetEntity(stream.Uid), out var xform) ||
            !stream.Source.SetPosition(_transform.GetWorldPosition(xform)))
            return;

        stream.Source.StartPlaying();
        _currentStreams.Add(stream);
}
```
т.к. в лобби нет карты и объемный звук будет не пойми где
т.е. вместо stream.Source.SetPosition должно быть stream.Source.SetGlobal(); если в лобби и Entity IsClientSide(uid) = true
например:
```
    private void ProcessEntityQueue(EntityUid uid)
    {
        if (TryTakeEntityStreamFromQueue(uid, out var stream))
            PlayEntity(stream, IsClientSide(uid));
    }
    private void PlayEntity(AudioStream stream, bool isLobbyOnly = false)
    {
        if (!_entity.TryGetComponent<TransformComponent>(GetEntity(stream.Uid), out var xform))
            return;

        if (_stateManager.CurrentState is Content.Client.Lobby.LobbyState && isLobbyOnly)
        {
            stream.Source.SetGlobal();
        }
        else if (!stream.Source.SetPosition(_transform.GetWorldPosition(xform)))
        {
            return;
        }

        stream.Source.StartPlaying();
        _currentStreams.Add(stream);
    }
```
