### ISSUE TITLE
Вернуть оригинальный код шлюзов

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1614]
### Описание

#263 
Почему?

### 1. Сломана логика.
У визардов при связывании двух шлюзов на болтирование, происходит следующее:
1. Первый шлюз начал открываться
2. Второй шлюз заболтирован
3. Первый шлюз открылся

В то время у нас:
1. Первый шлюз начал открываться
2. Первый шлюз открылся
3. Второй шлюз заболтирован

Что позволяет открыть и заболтировать две двери одновременно и без вмешательства инженеров не починить

### 2. Спрайты.
Вместо простой перерисовки стейтов, нужно делать дополнительные изменения, ведь есть доп стейты, что просто лишний гемор.

**Comment by 778b** [comment]
![Content Client_qElEAY1LZX](https://github.com/space-syndicate/space-station-14/assets/33431126/cc1df4f3-8826-4403-a112-80235f21d38a)
Щас в билде работает так как ты описал в "У визардов" болтирование происходит в начале анимации.

**Comment by lzk228** [comment]
перепроверю и закрою
