### ISSUE TITLE
Гайды, требующие перевода [На 15.12.2023]

### ISSUE THREAD

**Issue by lapatison** [space-syndicate/space-station-14#1642]
### [Антагонисты](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist)
- [x] [Антагонисты, Общий](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/Antagonists.xml)
- [x] [Антагонисты, Миноры](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/MinorAntagonists.xml)
- [x] [Антагонисты, Оперативники](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/Nuclear%20Operatives.xml)
- [x] [Антагонисты, Рева](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml)
- [x] [Антагонисты, Ниндзя](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml)
- [x] [Антагонисты, Предатели](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/Traitors.xml)
- [x] [Антагонисты, Зомби](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Antagonist/Zombies.xml)

### [Карго](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Cargo)
- [x] [Карго, Общий](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Cargo/Cargo.xml)
- [x] [Карго, Запросы (На ЦК)](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Cargo/CargoBounties.xml)

### [Управление](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Controls)
- [x] [Управление, Общий(На ЦК), Мало](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Controls/Controls.xml)
- [x] [Карго, Радио, Мало](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Controls/Radio.xml)

### [Инженерия](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering)
- [x] [ТЭГ](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering/TEG.xml)
- [x] [ПАКМАНЫ](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering/PortableGenerator.xml)
- [x] [Атмос, Мало](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering/Atmospherics.xml)
- [x] [Укрепление техпанелей шлюзов](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering/AirlockSecurity.xml)
- [x] [Конфигуратор доступов](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Engineering/AccessConfigurator.xml)

### [Медицина](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Medical)
- [x] [Продвинутые лекарства мехповреждений](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Medical/AdvancedBrute.xml)

### [Наука](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Science)
- [x] [Киборги](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Science/Cyborgs.xml)

### [СБ](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Security)
- [x] [ДНК, Строчка](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Security/DNA.xml)
- [x] [Дефуз](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Security/Defusal.xml)
[Черновик](https://github.com/lapatison/locale-station-14/blob/defusal-guidebook/Resources/ServerInfo/Guidebook/Security/Defusal.xml)*

### [Сервис](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Security)
- [x] [Бармен, Строчка](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Service/Bartender.xml)
- [x] [Ботаника](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Service/Botany.xml)

### [Прочее](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook)
- [x] [Выживание, Пара строчек](https://github.com/space-syndicate/space-station-14/tree/40ca6fb86b112f116bd70e79644d0753ee810949/Resources/ServerInfo/Guidebook/Survival.xml)

**Comment by lzk228** [comment]
@lapatison вроде готово
