### ISSUE TITLE
Некоторые черты внешности унатхов не совпадают с цветовой палитрой частей тела унатхов корвакса

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1748]

**Comment by MureixloI** [comment]
Сссассснули

**Comment by Jackal298** [comment]
Ну в целом тут выходит на свет проблема спрайтов корвакса для унатхов которых я думал, в целом тут вижу либо доработку спрайтов внешних, переработку цветовой палитры для унатхов, ну или же полный откат изменений спрайтов унатхов (хотя последние затронет и вульп, хотя в целом их можно перевести на стандартные спрайты)

**Comment by MureixloI** [comment]
> Ну в целом тут выходит на свет проблема спрайтов корвакса для унатхов а которых я думал, в целом тут вижу либо доработку спрайтов внешних, переработку цветовой палитры для унатхов, ну или же полный откат изменений спрайтов унатхов (хотя последние затронет и вульп, хотя в целом их можно перевести на стандартные спрайты)

Откат всё равно не мёрджеут

**Comment by Jackal298** [comment]
> > Ну в целом тут выходит на свет проблема спрайтов корвакса для унатхов а которых я думал, в целом тут вижу либо доработку спрайтов внешних, переработку цветовой палитры для унатхов, ну или же полный откат изменений спрайтов унатхов (хотя последние затронет и вульп, хотя в целом их можно перевести на стандартные спрайты)
> 
> Откат всё равно не мёрджеут

Ну значит остаются первый и второй вариант

**Comment by lzk228** [comment]
resolved by https://github.com/space-syndicate/space-station-14/pull/2248 #2353
