### ISSUE TITLE
У унатхов сломана одежда.

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1751]
Вероятно из-за нового префикса.
Нужно очень много переименовывания и замены в мета.джсон.

**Comment by lzk228** [comment]
Ошибся. Префикс тот же, но одежда всё равно обычная.

**Comment by CrazyCat2048** [comment]
> Ошибся. Префикс тот же, но одежда всё равно обычная.

Есть по итогу идея почему?

**Comment by lzk228** [comment]
Нет.
