### ISSUE TITLE
Две звуковые дорожки при BluespaceArtifact и AnomalySpawn

### ISSUE THREAD

**Issue by CrazyCat2048** [space-syndicate/space-station-14#1807]
### Описание

При появлении артефакта или аномалии во время случайного события addgamerule AnomalySpawn и addgamerule BluespaceArtifact воспроизводится две звуковые дорожки поверх друг друга.

### Шаги воспроизведения

1. addgamerule AnomalySpawn
2. addgamerule BluespaceArtifact

https://github.com/space-syndicate/space-station-14/assets/137882635/bf6a8d99-86ff-4ab2-b03d-e0593a2b2b93

**Comment by lzk228** [comment]
я посмотрел, происходит это из-за того, что в коде обьявлений, звук дефолтного обьявления `/Resources/Audio/Announcements/announce.ogg` заменён на корвакс обьявление центкома `/Resources/Audio/Corvax/Announcements/centcomm.ogg`, а в прототипе геймрула добавлен ещё начальный корваксный звук
единственный метод починить - дехардкодить эти геймрулы через оффов

**Comment by lzk228** [comment]
возможно я напиздел хуйни и дехардкодить нужно больше систем

**Comment by lzk228** [comment]
https://github.com/space-syndicate/space-station-14/assets/124214523/00530775-33b2-4b41-8101-2b5f708da3e4
