### ISSUE TITLE
Не работает злой двойник

### ISSUE THREAD

**Issue by CrazyCat2048** [space-syndicate/space-station-14#1808]
### Описание

Морти сказал, что злой двойник должен быть таким, как задумывался, поэтому надо фиксить 
Но, честно, сырая роль, которой не хватает механик и гейм дизайна

### Шаги воспроизведения

1. Создать злого двойника
2. Попробовать войти за гост роль
3. Неудачно. Двойник создался, SetMind не установился

**Comment by VigersRay** [comment]
интересно что злой двойник с билда нянотразен работает более чем адекватно.

**Comment by TheShuEd** [comment]
Я думаю учитывая что двойник ушел оффам, иссуе эту можно закрыть. это больше не проблема корвакса

**Comment by lzk228** [comment]
fixed :trollface:
