### ISSUE TITLE
Проблема игрового Changelogs

### ISSUE THREAD

**Issue by SonicHDC** [space-syndicate/space-station-14#1825]
### Описание

В данный момент у нас существует 3 раздела изменений в игре:
- Основные
- Corvax
- Админ
Сейчас же изменения что сделаны в нашей кодовой базе не логируются в раздел Corvax.
Нужно сменить где-то пути и/или дать небольшую документацию по изменениям в CL.

### Шаги воспроизведения

1. Сделать ПР с 🆑.
2. Зайти в игру.
3. Включить список обновлений Corvax.
4. Не найти новых обновлений.

**Comment by lzk228** [comment]
иан комрад бот в гитхабе не работает

**Comment by SonicHDC** [comment]
Вроде у них всё есть в игре, и даже админ 🆑  работает. Если не ошибаюсь.

**Comment by CrazyCat2048** [comment]
Вчера в канале maintainer видел, что тесты по логам на гите не работает

**Comment by lzk228** [comment]
не проблема репозитория

**Comment by SonicHDC** [comment]
Вот интересно, чего это тогда проблема?

**Comment by lzk228** [comment]
морти, ведь этого бота ещё и хостить нужно
