### ISSUE TITLE
черта внешности тигр ноги у унатхов не совпадает с ногами

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1840]
морти заебал
![Screenshot_20240203_025315](https://github.com/space-syndicate/space-station-14/assets/124214523/e1886df4-4bdf-4e94-828c-d9f1e027be47)
![Screenshot_20240203_025319](https://github.com/space-syndicate/space-station-14/assets/124214523/6ef65241-bf5e-4a9f-b89a-680e46bb5653)

**Comment by Hemomancer** [comment]
Мне больно.
