### ISSUE TITLE
нужен респрайт "махающихся" хвостов унатхов под палитру корвакса

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#1841]
заебал х2
![Screenshot_20240203_031821](https://github.com/space-syndicate/space-station-14/assets/124214523/a136c120-cfa8-4b90-8d67-1650ca9ba83e)
![Screenshot_20240203_031824](https://github.com/space-syndicate/space-station-14/assets/124214523/997ede80-3ddf-4d08-bf66-434a37a2aab2)

**Comment by Hemomancer** [comment]
Ну тут, к сонику надо.
