### ISSUE TITLE
ЕРРОРка при открытии заводных шлюзов и герметичных люков

### ISSUE THREAD

**Issue by mtrs163** [space-syndicate/space-station-14#1943]
### Описание

При открытии, заводные шлюзы и герметичные люки выдают ЕРРОРку

### Шаги воспроизведения

1. Открыть заводные шлюзы (неважно, стеклянный или нет) или герметичные люки (любые)
2. Получить еррорку

### Скриншоты

https://github.com/space-syndicate/space-station-14/assets/153596133/d95297a9-cf2b-40e4-ba4f-8becd4dbbe42

**Comment by MureixloI** [comment]
Там сейчас один из спрайтеров этим занимается

**Comment by pxc1984** [comment]
Морти это пофиксил месяц назад, исшуй можно закрывать.. [коммит](https://github.com/space-syndicate/space-station-14/commit/09763efc4afe548efa930303dbf1e226893eacbc)
