### ISSUE TITLE
Эвакуационный шаттл не может пристыковаться к Outpost

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#2261]
из-за этого фейлятся тесты

**Comment by lzk228** [comment]
по крайней мере один зафейлился
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/ac79ca0a-27a0-4c8f-bf9b-de89de1875cf)

**Comment by poeMota** [comment]
@SonicHDC
