### ISSUE TITLE
портировать КЗ в игровой гайдбук

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#2368]
ASAP!!!

**Comment by lzk228** [comment]
> bruh.

это правда
всё равно в итоге я сделаю :trollface:

**Comment by NotSoDana** [comment]
> > bruh.
> 
> это правда всё равно в итоге я сделаю :trollface:

Ну удачи тебе каждый раз кз переписывать с его обновлениями, хз, мазохист
