### ISSUE TITLE
Кривая система наложения одежды у Таракамолей

### ISSUE THREAD

**Issue by NotSoDana** [space-syndicate/space-station-14#2517]
title

![image](https://github.com/user-attachments/assets/99e4c940-8d51-4f14-840b-03a105a86512)
![image](https://github.com/user-attachments/assets/0f234d4a-396a-4947-af71-ecd1d0fc4f4e)
![image](https://github.com/user-attachments/assets/7d7aa5c1-16c9-49cd-8e4e-a1cc885dc2c3)
![image](https://github.com/user-attachments/assets/77e9a671-755c-4c00-8084-5e72b9acc4e0)

**Comment by MureixloI** [comment]
Эти таракопопы съели мне одежды, теперь я голая по станции бегаю
Зачем им кстати одежда?

**Comment by NotSoDana** [comment]
Зачем гамлету одежда?

**Comment by lzk228** [comment]
проблема апстрима
