### ISSUE TITLE
барная вывеска The Net требует локализации 

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#2527]
![thenet](https://github.com/user-attachments/assets/87c43873-fadc-496a-841d-974e1ce78a0a)

**Comment by CatBackGround** [comment]
Постараюсь на конце этой недели попытаться сделать это...
(Можете пиздить и срать мне в ДС)

**Comment by killervegetable** [comment]
Попробую сделать

**Comment by Verslebas** [comment]
Мне кажется этой вывеске локализация не нужна

**Comment by CatBackGround** [comment]
> Мне кажется этой вывеске локализация не нужна

Что тоже отчасти правда...

**Comment by CatBackGround** [comment]
> ![thenet](https://github.com/user-attachments/assets/87c43873-fadc-496a-841d-974e1ce78a0a)
> 

Я вообще, оффам.

**Comment by lzk228** [comment]
не требует ёпт
