### ISSUE TITLE
При добавлении ИИ на Silly он видит то, что не должен

### ISSUE THREAD

**Issue by mtrs163** [space-syndicate/space-station-14#2583]
### Описание

Если поставить ядро ИИ на карту Silly Island, а затем зайти за него, он будет видеть некоторые тайлы и сущности, находящиеся за пределами его поля зрения.

### Шаги воспроизведения

1. Поставить ядро ИИ на Silly Island
2. Дебаг -> ИИ Захват
3. Полетать по станции и увидеть приколы со скриншота

### Скриншоты

![SS14 Loader_hd1nHbSATj](https://github.com/user-attachments/assets/c729f2ac-e720-4141-ac5d-b8154804bedf)

**Comment by NotSoDana** [comment]
А на кой хуй ИИ на силли спрашивается и кто его туда добавлять собрался

**Comment by lzk228** [comment]
на силли нет ИИ
