### ISSUE TITLE
Неправильное отображение плазмы в протолате

### ISSUE THREAD

**Issue by Morb0** [space-syndicate/space-station-14#259]
### Описание

Плазма имеет несколько стейтов для анимации, но в протолате отображается просто как текстура.

### Шаги воспроизведения

1. Добавить плазму в протолат
2. Открыть меню протолата

### Скриншоты

<img width="297" src="https://user-images.githubusercontent.com/14136326/173910290-f62f762b-19fa-41f9-84f2-a2dc0d456ead.png">

**Comment by LarryRussian** [comment]
А может просто запретить плазму вставлять?

**Comment by LarryRussian** [comment]
![image](https://user-images.githubusercontent.com/98099652/182149591-52e70a83-7f1e-4149-af22-c2360e2e6e79.png)
Текстура не правильная, надо заменить, заменю.

**Comment by Morb0** [comment]
Все там правильно, я описал в чем конкретно проблема.

**Comment by LarryRussian** [comment]
У неё расширение gif должна быть?

**Comment by LarryRussian** [comment]
Морбо, какой предмет который есть в игре можно засунуть в печку/протолат, а так же он имеет анимацию?

**Comment by Morb0** [comment]
Никакой. Если это было так просто я бы сделал и сам.

**Comment by LarryRussian** [comment]
Я уже понял.

**Comment by Morb0** [comment]
Можно считать пофикшенным в https://github.com/space-syndicate/space-station-14/commit/69971272e6e1d1310e502cd8181e11678b758b91
![image](https://user-images.githubusercontent.com/14136326/210400559-7d89ed92-06ba-46a8-bbb2-8acad64690de.png)
