### ISSUE TITLE
на пильгриме нету тележек для еды

### ISSUE THREAD

**Issue by lzk228** [space-syndicate/space-station-14#2730]

**Comment by kosticia** [comment]
Да, это явно стоит написания ишшуя, писать в написать в ветку карты в дискорде, видать, для неудачников

**Comment by Meguneri** [comment]
Невероятно

**Comment by cfif126** [comment]
Нифига? А так можно открывать ишью ради изменения на карте?

**Comment by Ko4ergaPunk** [comment]
[_злобно мяукает_](https://discord.com/channels/919301044784226385/1252282320690352229)
