### ISSUE TITLE
ошибка при запуске RUN_THIS.py

### ISSUE THREAD

**Issue by sladkiimaksimka** [space-syndicate/space-station-14#312]
### Описание

при запуске происходит такая проблема: fatal: not a git repository (or any of the parent directories): .git

### Шаги воспроизведения

python RUN_THIS.py
или
C:/Users/Maxim/AppData/Local/Programs/Python/Python37/python.exe "c:/Users/Maxim/Desktop/bebranuh server RUS/RUN_THIS.py"

### Скриншоты

![image](https://user-images.githubusercontent.com/99991427/179424074-b90dc2af-c710-45b5-b28b-afbc885a5509.png)

**Comment by Morb0** [comment]
Нужно команду выполнять в папке `space-station-14`. Команда `cd` поможет решить проблему - http://cmd4win.ru/administrirovanie-computera/upravlenie-failami/29-cd
