### ISSUE TITLE
Неправильное отображение открытого внешнего шлюза

### ISSUE THREAD

**Issue by Morb0** [space-syndicate/space-station-14#394]
### Описание

Зеленные огни шлюза горят все время пока он открыт, хотя должны скрываться после окончания анимации открытия и останутся только синии огни питания.
Проблема скорее всего в логике после обновления `AirlockVisualizer` - https://github.com/space-syndicate/space-station-14/pull/383/commits/3c918a374be190be25da36fdcf29f2754886ac81

### Шаги воспроизведения

1. Открыть внешний красный шлюз
2. Подождать анимацию открытия

### Скриншоты

![image](https://user-images.githubusercontent.com/14136326/189772680-46144672-4ca7-4708-b5b2-acb1d4c19715.png) ![image](https://user-images.githubusercontent.com/14136326/190245187-b8f91fe2-7215-4c71-b2c5-d8031ad50902.png)

**Comment by 778b** [comment]
#984 Это же правильное решение, у вас у этих шлюзов щас не подсвечивается unlit как у оффициалов поэтому и у закрытого шлюза и у открытого шлюза unlit не отображается, из-за чего показывается последний кадр анимации, а чтобы подсвечивался надо как раз добавить эти строчки чтобы отображался unlit как у остальных шлюзов.

**Comment by lzk228** [comment]
внешний шлюз выглядит починеным, бронированый будет починен после #1923

https://github.com/space-syndicate/space-station-14/assets/124214523/dcababdb-fca0-4b90-81ac-b1b325ce8d00

видео снято на https://github.com/space-syndicate/space-station-14/pull/1923/commits/499b119d5d42ca66140b20e35ba1b01375af3662
