### ISSUE TITLE
Мерцание экрана

### ISSUE THREAD

**Issue by UZaliv** [space-syndicate/space-station-14#445]
### Описание

Если подойти к сингулярности то всё вокруг начнёт мерцать, но ести включить "изображения низково разрешения" экран не мерцает.

### Шаги воспроизведения

1.Открыть настройки графики и выключить изображение низкого разрешения.
2.Подойти к сингулярности.
3.Экран мерцает.

### Скриншоты

![image](https://user-images.githubusercontent.com/115162412/194540232-91d68f01-9097-400c-8715-634ea66aeb9d.png)

**Comment by Normone** [comment]
Присоединяюсь. Аналогичная проблема, но без сингулярности. Просто ни с того, ни с сего сломалось освещение и начало быстро мерцать. Перезапуск игры не помог, так что 90% шанс что проблема с моей стороны. У вас никакие железки после возникновения этой проблемы не умирали? Мб хард или видеокарта?
