### ISSUE TITLE
Опрокидывание спрайта куклы при укусе паука

### ISSUE THREAD

**Issue by Marya-The-Slime** [space-syndicate/space-station-14#684]
### Описание

Я добавил паукам укус, который наносит 15 урона проникновения и 7 яда ( эти цифры и значения, как и анимация атаки никак не влияют на результат). При укусе, спрайт человека переворачивается на 90 градусов.
Отныне человек при атаке кого-то в рукопашную переворачивает спрайты атакованных на 90 градусов
При этом, если человек сядет на стул - спрайт восстановится и атаки больше не будут переворачивать, как и атака изменённого паука по человеке. 

### Шаги воспроизведения

1. Добавить паукам атаку
2. Запустить локальный сервер
3. Заспавнить изменённого паука
4. Атаковать куклу человека изменённым пауком (работает и на других спрайтах, но гигакрыс не переворачивается)
5. Сесть человеком на стул

### Скриншоты

![Скриншот 28 12 22_15 53 48](https://user-images.githubusercontent.com/96390365/209866637-54adb3f5-8d06-4eb9-af77-89d73a3d5766.jpg)
![Скриншот 28 12 22_15 53 36](https://user-images.githubusercontent.com/96390365/209866639-242e6231-b195-47f7-92b8-8fe95cc7408a.jpg)

**Comment by Morb0** [comment]
Я не думаю, что это проблема именно нашей сборки. Если это не так, то переоткрой.
