### ISSUE TITLE
Контекстные меню объектов

### ISSUE THREAD

**Issue by dontbetank** [space-syndicate/space-station-14#734]
### Описание

При открытии контекстного меню на ПКМ, появляется только несколько пунктов. Это не даёт, к примеру, повернуть объект, а администрации применить наказания на персонаже игрока. Также появляется пункт "Ожидание сервера" до этого возникавший только при проблемах с соединением. При это всё играется и игровые действия можно спокойно совершать.
К появляющимся пунктам меню можно отнести:

- Осмотры всех видов
- Перетаскивание объекта
- Указывание на объект
- Единственный подпункт "View Variables" пункта "Debug"
- Следование за объектом, будучи призраком

Появление проблемы подозрительно совпало с вводом функции TTS.

### Шаги воспроизведения

1. Зайти в игру за своего персонажа или призрака
2. Кликнуть на любой объект на карте правой кнопкой мыши

### Скриншоты

![изображение](https://user-images.githubusercontent.com/59025279/212169224-b2903363-04f0-418d-a06c-faecf9139ac7.png)

**Comment by Morb0** [comment]
Исправлено https://github.com/space-wizards/space-station-14/pull/13454
